/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import javax.swing.JOptionPane;
import AppPackage.AnimationClass;


/**
 *
 * @author josue
 */
public class Inicio extends javax.swing.JFrame {
    

    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpControlPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPHome = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jbtncerrar = new javax.swing.JButton();
        jbtminimizar = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPBackground = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpControlPanel.setOpaque(false);
        jpControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/icons8-corintios-50.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/icons8-el-campo-de-baloncesto-50.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/icons8-copa-del-mundo-50.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/icons8-cabeza-a-cabeza-24.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/icons8-cambio-jugador-filled-50.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/icons8-fútbol-50.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jpControlPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 260, 150, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Sign_Out_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Sign_Out_32px_1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jpControlPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 50, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jpControlPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 140, 150, 20));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(111, 174, 2));
        jLabel8.setText("Mundial");
        jpControlPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 350, 160, 40));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(111, 174, 2));
        jLabel7.setText("Estadio");
        jpControlPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 290, 120, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jpControlPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 199, 150, 20));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(111, 174, 2));
        jLabel6.setText("Grupo");
        jpControlPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 240, 120, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(111, 174, 2));
        jLabel5.setText("Partido");
        jpControlPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 180, 120, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(111, 174, 2));
        jLabel4.setText("Equipos");
        jLabel4.setToolTipText("");
        jpControlPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 120, 120, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jpControlPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 308, 150, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jpControlPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 370, 190, 20));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(111, 174, 2));
        jLabel3.setText("Jugadores");
        jpControlPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 60, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Menu_32px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jpControlPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jpControlPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 80, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PANEL.png"))); // NOI18N
        jpControlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 230, 497));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/expandir.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpControlPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 40, -1));

        getContentPane().add(jpControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 497));

        jPHome.setOpaque(false);
        jPHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Home");
        jPHome.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator1.setForeground(new java.awt.Color(111, 174, 2));
        jPHome.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 850, 10));

        jSeparator2.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator2.setForeground(new java.awt.Color(111, 174, 2));
        jPHome.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 335, 850, 10));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/images (1).png"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 357, 120, 140));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/Logo_of_AC_Milan.svg.png"))); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 357, 130, 140));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/1844.png"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 357, 120, 140));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/65.png"))); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 357, 130, 140));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/Escudo_de_la_Federación_Colombiana_de_Fútbol.png"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 130, 140));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/d4683dc83b4b52bfa3105548abc0a565.png"))); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, 140));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/665c87a24ab9a76d384bc3cc5981d70c.png"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 130, 140));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/FC_Bayern_München_logo_(2017).svg.png"))); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 120, 140));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Equipos Destacados");
        jPHome.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 94, -1, -1));

        jbtncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px.png"))); // NOI18N
        jbtncerrar.setBorder(null);
        jbtncerrar.setBorderPainted(false);
        jbtncerrar.setContentAreaFilled(false);
        jbtncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtncerrarMouseClicked(evt);
            }
        });
        jbtncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncerrarActionPerformed(evt);
            }
        });
        jPHome.add(jbtncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 50, 50));

        jbtminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jbtminimizar.setBorder(null);
        jbtminimizar.setBorderPainted(false);
        jbtminimizar.setContentAreaFilled(false);
        jbtminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtminimizarMouseClicked(evt);
            }
        });
        jbtminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtminimizarActionPerformed(evt);
            }
        });
        jPHome.add(jbtminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 50));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/b10aedca4a535e5fa4551decba8474e5f75b2818.png"))); // NOI18N
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 120, 140));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/67.png"))); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        jPHome.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 357, 120, 140));

        getContentPane().add(jPHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 930, 500));

        jPBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loginbueno.png"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        jPBackground.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtncerrarActionPerformed

    private void jbtminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtminimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtminimizarActionPerformed

    private void jbtminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtminimizarMouseClicked
        setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_jbtminimizarMouseClicked

    private void jbtncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtncerrarMouseClicked
         try{
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea Cerrar el Sistema?","EXIT",dialogButton);
        if(result == 0){
            System.exit(0);
        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jbtncerrarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AnimationClass izq1 = new AnimationClass();
        izq1.jLabelXLeft(30, -150, 18, 10, jLabel3);
        
        AnimationClass izq2 = new AnimationClass();
        izq2.jLabelXLeft(30, -150, 18, 10, jLabel4);
        
        AnimationClass izq3 = new AnimationClass();
        izq3.jLabelXLeft(30, -150, 18, 10, jLabel5);
        
        AnimationClass izq4 = new AnimationClass();
        izq4.jLabelXLeft(30, -150, 18, 10, jLabel6);
        
        AnimationClass izq5 = new AnimationClass();
        izq5.jLabelXLeft(30, -150, 18, 10, jLabel7);
        
        AnimationClass izq6 = new AnimationClass();
        izq6.jLabelXLeft(30, -150, 18, 10, jLabel8);
        
        AnimationClass izq7 = new AnimationClass();
        izq7.jLabelXLeft(0, -160, 18, 10, jLabel1);
        //here
        AnimationClass izq8 = new AnimationClass();
        izq8.jLabelXLeft(180, 20 , 18, 10, jLabel2);
        
        AnimationClass derecha9 = new AnimationClass();
        derecha9.jLabelXLeft(170, 10 , 18, 10, jLabel9);
        
        AnimationClass derecha10 = new AnimationClass();
        derecha10.jLabelXLeft(170, 10 , 18, 10, jLabel10);
        
        AnimationClass derecha11 = new AnimationClass();
        derecha11.jLabelXLeft(180, 20 , 18, 10, jLabel14);
        
        AnimationClass derecha12 = new AnimationClass();
        derecha12.jLabelXLeft(170, 10 , 18, 10, jLabel11);
        
        AnimationClass derecha13 = new AnimationClass();
        derecha13.jLabelXLeft(170, 10 , 18, 10, jLabel12);
        
        AnimationClass derecha14 = new AnimationClass();
        derecha14.jLabelXLeft(170, 10 , 18, 10, jLabel13);
        
        AnimationClass derecha15 = new AnimationClass();
        derecha15.jButtonXLeft(170, 10 , 18, 10, jButton1);
        
        AnimationClass izq16 = new AnimationClass();
        izq16.jButtonXLeft(220, 60 , 18, 10, jButton2);
        
        AnimationClass izq17 = new AnimationClass();
        izq17.jLabelXLeft(-20, -220 , 18, 10, jLabel15);
    
        AnimationClass izq18 = new AnimationClass();
        izq18.jLabelXLeft(-20, -220 , 18, 10, jLabel16);
        
        AnimationClass izq19 = new AnimationClass();
        izq19.jLabelXLeft(-20, -220 , 18, 10, jLabel17);
        
        AnimationClass izq20 = new AnimationClass();
        izq20.jLabelXLeft(-20, -220 , 18, 10, jLabel18);
        
        AnimationClass izq21 = new AnimationClass();
        izq21.jLabelXLeft(-20, -220 , 18, 10, jLabel19);
        
        AnimationClass izq22 = new AnimationClass();
        izq22.jLabelXLeft(-20, -220 , 18, 10, jLabel20);
        
        
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        AnimationClass derecha1 = new AnimationClass();
        derecha1.jLabelXRight(-150, 30, 18, 10, jLabel3);
        
        AnimationClass derecha2 = new AnimationClass();
        derecha2.jLabelXRight(-150, 30, 18, 10, jLabel4);
        
        AnimationClass derecha3 = new AnimationClass();
        derecha3.jLabelXRight(-150, 30, 18, 10, jLabel5);
        
        AnimationClass derecha4 = new AnimationClass();
        derecha4.jLabelXRight(-150, 30, 18, 10, jLabel6);
        
        AnimationClass derecha5 = new AnimationClass();
        derecha5.jLabelXRight(-150, 30, 18, 10, jLabel7);
        
        AnimationClass derecha6 = new AnimationClass();
        derecha6.jLabelXRight(-150, 30, 18, 10, jLabel8);
        
        AnimationClass derecha7 = new AnimationClass();
        derecha7.jLabelXRight(-160, 0, 18, 10, jLabel1);
        
        AnimationClass derecha8 = new AnimationClass();
        derecha8.jLabelXRight(20, 180 , 18, 10, jLabel2);
        
        AnimationClass derecha9 = new AnimationClass();
        derecha9.jLabelXRight(10, 170 , 18, 10, jLabel9);
        
        AnimationClass derecha10 = new AnimationClass();
        derecha10.jLabelXRight(10, 170 , 18, 10, jLabel10);
        
        AnimationClass derecha11 = new AnimationClass();
        derecha11.jLabelXRight(20, 180 , 18, 10, jLabel14);
        
        AnimationClass derecha12 = new AnimationClass();
        derecha12.jLabelXRight(10, 170 , 18, 10, jLabel11);
        
        AnimationClass derecha13 = new AnimationClass();
        derecha13.jLabelXRight(10, 170 , 18, 10, jLabel12);
        
        AnimationClass derecha14 = new AnimationClass();
        derecha14.jLabelXRight(10, 170 , 18, 10, jLabel13);
        
        AnimationClass derecha15 = new AnimationClass();
        derecha15.jButtonXRight(10, 170 , 18, 10, jButton1);
        
        AnimationClass derecha16 = new AnimationClass();
        derecha16.jButtonXRight(60, 220 , 18, 10, jButton2);
        
        AnimationClass derecha17 = new AnimationClass();
        derecha17.jLabelXRight(-220, -20 , 18, 10, jLabel15);
        
        AnimationClass derecha18 = new AnimationClass();
        derecha18.jLabelXRight(-220, -20 , 18, 10, jLabel16);
        
        AnimationClass derecha19 = new AnimationClass();
        derecha19.jLabelXRight(-220, -20 , 18, 10, jLabel17);
        
        AnimationClass derecha20 = new AnimationClass();
        derecha20.jLabelXRight(-220, -20 , 18, 10, jLabel18);
        
        AnimationClass derecha21 = new AnimationClass();
        derecha21.jLabelXRight(-220, -20 , 18, 10, jLabel19);
        
        AnimationClass derecha22 = new AnimationClass();
        derecha22.jLabelXRight(-220, -20 , 18, 10, jLabel20);
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        AnimationClass derecha1 = new AnimationClass();
        derecha1.jLabelXRight(-150, 30, 18, 10, jLabel3);
        
        AnimationClass derecha2 = new AnimationClass();
        derecha2.jLabelXRight(-150, 30, 18, 10, jLabel4);
        
        AnimationClass derecha3 = new AnimationClass();
        derecha3.jLabelXRight(-150, 30, 18, 10, jLabel5);
        
        AnimationClass derecha4 = new AnimationClass();
        derecha4.jLabelXRight(-150, 30, 18, 10, jLabel6);
        
        AnimationClass derecha5 = new AnimationClass();
        derecha5.jLabelXRight(-150, 30, 18, 10, jLabel7);
        
        AnimationClass derecha6 = new AnimationClass();
        derecha6.jLabelXRight(-150, 30, 18, 10, jLabel8);
        
        AnimationClass derecha7 = new AnimationClass();
        derecha7.jLabelXRight(-160, 0, 18, 10, jLabel1);
        
        AnimationClass derecha8 = new AnimationClass();
        derecha8.jLabelXRight(20, 180 , 18, 10, jLabel2);
        
        AnimationClass derecha9 = new AnimationClass();
        derecha9.jLabelXRight(10, 170 , 18, 10, jLabel9);
        
        AnimationClass derecha10 = new AnimationClass();
        derecha10.jLabelXRight(10, 170 , 18, 10, jLabel10);
        
        AnimationClass derecha11 = new AnimationClass();
        derecha11.jLabelXRight(20, 180 , 18, 10, jLabel14);
        
        AnimationClass derecha12 = new AnimationClass();
        derecha12.jLabelXRight(10, 170 , 18, 10, jLabel11);
        
        AnimationClass derecha13 = new AnimationClass();
        derecha13.jLabelXRight(10, 170 , 18, 10, jLabel12);
        
        AnimationClass derecha14 = new AnimationClass();
        derecha14.jLabelXRight(10, 170 , 18, 10, jLabel13);
        
        AnimationClass derecha15 = new AnimationClass();
        derecha15.jButtonXRight(10, 170 , 18, 10, jButton1);
        
        AnimationClass derecha16 = new AnimationClass();
        derecha16.jButtonXRight(60, 220 , 18, 10, jButton2);
        
        AnimationClass derecha17 = new AnimationClass();
        derecha17.jLabelXRight(-220, -20 , 18, 10, jLabel15);
        
        AnimationClass derecha18 = new AnimationClass();
        derecha18.jLabelXRight(-220, -20 , 18, 10, jLabel16);
        
        AnimationClass derecha19 = new AnimationClass();
        derecha19.jLabelXRight(-220, -20 , 18, 10, jLabel17);
        
        AnimationClass derecha20 = new AnimationClass();
        derecha20.jLabelXRight(-220, -20 , 18, 10, jLabel18);
        
        AnimationClass derecha21 = new AnimationClass();
        derecha21.jLabelXRight(-220, -20 , 18, 10, jLabel19);
        
        AnimationClass derecha22 = new AnimationClass();
        derecha22.jLabelXRight(-220, -20 , 18, 10, jLabel20);
        
        

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Login login = new Login();
        dispose(); // desaparece login
        login.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

            Jugador1 jugador = new Jugador1();
            dispose(); // Cierra la ventana de login
            jugador.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

            Equipo equipo = new Equipo();
            dispose(); // Cierra la ventana de login
            equipo.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked

            Partido partido = new Partido();
            dispose(); // Cierra la ventana de login
            partido.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

            Grupo grupo = new Grupo();
            dispose(); // Cierra la ventana de login
            grupo.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

            Estadio carro = new Estadio();
            dispose(); // Cierra la ventana de login
            carro.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

            Mundial estadisticas = new Mundial();
            dispose(); // Cierra la ventana de login
            estadisticas.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPHome;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtminimizar;
    private javax.swing.JButton jbtncerrar;
    private javax.swing.JPanel jpControlPanel;
    // End of variables declaration//GEN-END:variables
}
