/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import Class.GRUPO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Mundial extends javax.swing.JFrame {
    private static ArrayList<GRUPO> gruposmundialtotal = new ArrayList<>();
    private static ArrayList<String> gruposmundial = new ArrayList<>();
    private static ArrayList<GRUPO> gruposmundial1 = new ArrayList<>();

    
    public Mundial() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel2.setBackground(new Color(0,0,0,70));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCombojugadores = new javax.swing.JComboBox<>();
        jButtonAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_iniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jBMinimizar = new javax.swing.JButton();
        jBBackToinicio1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlBackground1 = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCombojugadores.setBackground(new java.awt.Color(4, 4, 4));
        jCombojugadores.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jCombojugadores.setForeground(new java.awt.Color(0, 153, 0));
        jCombojugadores.setBorder(null);
        jCombojugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCombojugadores.setOpaque(true);
        jCombojugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombojugadoresActionPerformed(evt);
            }
        });
        jPanel2.add(jCombojugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 50));

        jButtonAgregar.setBackground(new java.awt.Color(4, 4, 4));
        jButtonAgregar.setForeground(new java.awt.Color(4, 4, 4));
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/ANADIR_OFF.png"))); // NOI18N
        jButtonAgregar.setBorder(null);
        jButtonAgregar.setContentAreaFilled(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.setOpaque(true);
        jButtonAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/ANADIR_ON.png"))); // NOI18N
        jButtonAgregar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/ANADIR_ON.png"))); // NOI18N
        jButtonAgregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/ANADIR_ON.png"))); // NOI18N
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MUNDIAL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, 20));

        jSeparator2.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator2.setForeground(new java.awt.Color(111, 174, 2));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 30, 250));

        jButton_iniciar.setBackground(new java.awt.Color(4, 4, 4));
        jButton_iniciar.setForeground(new java.awt.Color(4, 4, 4));
        jButton_iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_OFF.png"))); // NOI18N
        jButton_iniciar.setBorder(null);
        jButton_iniciar.setBorderPainted(false);
        jButton_iniciar.setContentAreaFilled(false);
        jButton_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_iniciar.setOpaque(true);
        jButton_iniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_ON.png"))); // NOI18N
        jButton_iniciar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_ON.png"))); // NOI18N
        jButton_iniciar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_ON.png"))); // NOI18N
        jButton_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_iniciarMouseClicked(evt);
            }
        });
        jPanel2.add(jButton_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 50, -1));

        jTextArea1.setBackground(new java.awt.Color(4, 4, 4));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 410, 260));

        jSeparator4.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator4.setForeground(new java.awt.Color(111, 174, 2));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 350, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 820, 380));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jBMinimizar.setBorder(null);
        jBMinimizar.setBorderPainted(false);
        jBMinimizar.setContentAreaFilled(false);
        jBMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jBMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 40));

        jBBackToinicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        jBBackToinicio1.setBorder(null);
        jBBackToinicio1.setBorderPainted(false);
        jBBackToinicio1.setContentAreaFilled(false);
        jBBackToinicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBackToinicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBackToinicio1MouseClicked(evt);
            }
        });
        jPanel1.add(jBBackToinicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loginbueno.png"))); // NOI18N
        jPanel3.add(jlBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 440));

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loginbueno.png"))); // NOI18N
        jPanel3.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCombojugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombojugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombojugadoresActionPerformed

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        if (gruposmundial.size() < 2) {
        String grupoSeleccionado = (String) jCombojugadores.getSelectedItem();
        if (!gruposmundial.contains(grupoSeleccionado)) {
            gruposmundial.add(grupoSeleccionado);
            for (GRUPO grupoen : gruposmundialtotal) {
                if (grupoen.getNombre().equalsIgnoreCase(grupoSeleccionado)) {
                    gruposmundial1.add(grupoen);
                }
            }
            JOptionPane.showMessageDialog(null, grupoSeleccionado + " ha sido agregado al mundial.");
        } else {
            JOptionPane.showMessageDialog(null, grupoSeleccionado + " ya está en el mundial.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "El mundial ya tiene 2 grupos.");
    }
    }//GEN-LAST:event_jButtonAgregarMouseClicked

    private void jButton_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_iniciarMouseClicked
        if (gruposmundial.size() % 2 != 0) {
        JOptionPane.showMessageDialog(null, "La cantidad de grupos debe ser par para generar el fixture.");
        return;
    }

    // Generar Fixture
    StringBuilder fixture = new StringBuilder();
    for (String grupoNombre : gruposmundial) {
        // Mensaje de depuración
        System.out.println("Procesando grupo: " + grupoNombre);
        
        GRUPO grupo = gruposmundial1.stream().filter(g -> g.getNombre().equals(grupoNombre)).findFirst().orElse(null);
        
        if (grupo != null) {
            fixture.append("Fixture de ").append(grupoNombre).append(":\n");
            List<String> equipos = grupo.getEquipos();
            int numEquipos = equipos.size();
            for (int i = 0; i < numEquipos - 1; i++) {
                for (int j = i + 1; j < numEquipos; j++) {
                    fixture.append(equipos.get(i)).append(" vs ").append(equipos.get(j)).append("\n");
                }
            }
            fixture.append("\n");
        } else {
            // Mensaje de depuración
            System.out.println("El grupo no se encontró: " + grupoNombre);
        }
    }
    
    // Mensaje de depuración
    System.out.println("Fixture generado:\n" + fixture.toString());
    
    jTextArea1.setText(fixture.toString());
    }//GEN-LAST:event_jButton_iniciarMouseClicked

    private void jBBackToinicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackToinicio1MouseClicked
        Inicio inicio = new Inicio();
        dispose(); // Cierra la ventana de login
        inicio.setVisible(true);
    }//GEN-LAST:event_jBBackToinicio1MouseClicked

    private void jBMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMinimizarMouseClicked
        this.setState(yFrame.Login.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<String> equiposGrupoA = new ArrayList<>(Arrays.asList("Equipo A1", "Equipo A2", "Equipo A3", "Equipo A4", "Equipo A5", "Equipo A6"));
        GRUPO grupoA = new GRUPO("Grupo A", equiposGrupoA);

        // Segundo grupo
        ArrayList<String> equiposGrupoB = new ArrayList<>(Arrays.asList("Equipo B1", "Equipo B2", "Equipo B3", "Equipo B4", "Equipo B5", "Equipo B6"));
        GRUPO grupoB = new GRUPO("Grupo B", equiposGrupoB);

        // Tercer grupo
        ArrayList<String> equiposGrupoC = new ArrayList<>(Arrays.asList("Equipo C1", "Equipo C2", "Equipo C3", "Equipo C4", "Equipo C5", "Equipo C6"));
        GRUPO grupoC = new GRUPO("Grupo C", equiposGrupoC);
        
        jCombojugadores.addItem(grupoA.getNombre());
        gruposmundialtotal.add(grupoA);
        jCombojugadores.addItem(grupoB.getNombre());
        gruposmundialtotal.add(grupoB);
        jCombojugadores.addItem(grupoC.getNombre());
        gruposmundialtotal.add(grupoC);
        for (GRUPO grupos: Grupo.getGrupos()) {
            jCombojugadores.addItem(grupos.getNombre());
            gruposmundialtotal.add(grupos);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mundial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mundial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBackToinicio1;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButton_iniciar;
    private javax.swing.JComboBox<String> jCombojugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlBackground1;
    // End of variables declaration//GEN-END:variables
}
