/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yFrame;

import Class.Jugador;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Partido extends javax.swing.JFrame {
    private static ArrayList<String> contrincantes = new ArrayList<>();

   public static ArrayList<String> getcontrincantes() {
    return contrincantes;
}

    private ArrayList<String> jugadoresDisponibles;

    public Partido() {
        initComponents();
        jugadoresDisponibles = obtenerJugadoresDisponibles();
        cargarJugadores(jCombojugadores, jugadoresDisponibles);
        cargarJugadores(jCombojugadores1, jugadoresDisponibles);
        this.setLocationRelativeTo(null);
        jPanel2.setBackground(new Color(0,0,0,70));
    }

    private ArrayList<String> obtenerJugadoresDisponibles() {
        ArrayList<String> equipos = new ArrayList<>();
        equipos.add("FC Barcelona");
        equipos.add("Real Madrid");
        equipos.add("Paris Saint-Germain");
        equipos.add("Manchester City");
        equipos.add("Liverpool FC");
        equipos.add("Bayern Munich");
        equipos.add("Juventus FC");
        equipos.add("Chelsea FC");
        equipos.add("Manchester United");
        equipos.add("Atletico Madrid");
        equipos.add("Borussia Dortmund");
        equipos.add("Inter Milan");
        equipos.add("AC Milan");
        equipos.add("Tottenham Hotspur");
        equipos.add("AS Roma");
        equipos.add("Arsenal FC");
        equipos.add("Sevilla FC");
        equipos.add("Napoli");
        equipos.add("Ajax");
        equipos.add("Lazio");
        
        // Añadir jugadores registrados por los usuarios
        for (Jugador jugador : Jugador1.getjugadores()) {
            equipos.add(jugador.getNombre());
        }
        return equipos;
    }

    private void cargarJugadores(JComboBox<String> comboBox, ArrayList<String> jugadores) {
        for (String jugador : jugadores) {
            comboBox.addItem(jugador);
        }
    }

    private void seleccionarJugador() {
        String jugadorSeleccionado = (String) jCombojugadores.getSelectedItem();

        // Eliminar jugadorSeleccionado de jCombojugadores1
        eliminarJugadorDeComboBox(jugadorSeleccionado, jCombojugadores1);

        // Mostrar mensaje o realizar otras operaciones según sea necesario
        JOptionPane.showMessageDialog(null, "Jugador seleccionado: " + jugadorSeleccionado);
    }

    private void eliminarJugadorDeComboBox(String jugador, JComboBox<String> comboBox) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (jugador.equals(comboBox.getItemAt(i))) {
                comboBox.removeItemAt(i);
                break; // Salir del bucle una vez eliminado el jugador
            }
        }
    }
    
    /**
     * Creates new form Monitores
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCombojugadores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_iniciar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jCombojugadores1 = new javax.swing.JComboBox<>();
        jPHome2 = new javax.swing.JPanel();
        jBMinimizar = new javax.swing.JButton();
        jBBackToinicio1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCombojugadores.setBackground(new java.awt.Color(4, 4, 4));
        jCombojugadores.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jCombojugadores.setForeground(new java.awt.Color(0, 153, 0));
        jCombojugadores.setBorder(null);
        jCombojugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCombojugadores.setOpaque(true);
        jCombojugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombojugadoresActionPerformed(evt);
            }
        });
        jPanel2.add(jCombojugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 200, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PARTIDO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, 20));

        jSeparator2.setBackground(new java.awt.Color(111, 174, 2));
        jSeparator2.setForeground(new java.awt.Color(111, 174, 2));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 350, 10));

        jButton_iniciar.setBackground(new java.awt.Color(4, 4, 4));
        jButton_iniciar.setForeground(new java.awt.Color(4, 4, 4));
        jButton_iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_OFF.png"))); // NOI18N
        jButton_iniciar.setBorder(null);
        jButton_iniciar.setBorderPainted(false);
        jButton_iniciar.setContentAreaFilled(false);
        jButton_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_iniciar.setOpaque(true);
        jButton_iniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_ON.png"))); // NOI18N
        jButton_iniciar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_ON.png"))); // NOI18N
        jButton_iniciar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GO_LOG_ON.png"))); // NOI18N
        jButton_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_iniciarMouseClicked(evt);
            }
        });
        jPanel2.add(jButton_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 50, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/line.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 270, 20));

        jCombojugadores1.setBackground(new java.awt.Color(4, 4, 4));
        jCombojugadores1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jCombojugadores1.setForeground(new java.awt.Color(0, 153, 0));
        jCombojugadores1.setBorder(null);
        jCombojugadores1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCombojugadores1.setOpaque(true);
        jCombojugadores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombojugadores1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCombojugadores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 820, 380));

        jPHome2.setOpaque(false);
        jPHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jBMinimizar.setBorder(null);
        jBMinimizar.setBorderPainted(false);
        jBMinimizar.setContentAreaFilled(false);
        jBMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMinimizarMouseClicked(evt);
            }
        });
        jPHome2.add(jBMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 40));

        jBBackToinicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        jBBackToinicio1.setBorder(null);
        jBBackToinicio1.setBorderPainted(false);
        jBBackToinicio1.setContentAreaFilled(false);
        jBBackToinicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBackToinicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBackToinicio1MouseClicked(evt);
            }
        });
        jPHome2.add(jBBackToinicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 40));

        getContentPane().add(jPHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loginbueno.png"))); // NOI18N
        jPanel1.add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMinimizarMouseClicked
        this.setState(yFrame.Login.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarMouseClicked

    private void jBBackToinicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackToinicio1MouseClicked
        Inicio inicio = new Inicio();
        dispose(); // Cierra la ventana de login
        inicio.setVisible(true);
    }//GEN-LAST:event_jBBackToinicio1MouseClicked

    private void jCombojugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombojugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombojugadoresActionPerformed

    private void jButton_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_iniciarMouseClicked
      String e1 = (String) jCombojugadores.getSelectedItem(); 
      String e2 = (String) jCombojugadores1.getSelectedItem(); 
      contrincantes.add(e1);
      contrincantes.add(e2);
      Match match = new Match();
            dispose(); // Cierra la ventana de login
            match.setVisible(true);
      
      
    }//GEN-LAST:event_jButton_iniciarMouseClicked

    private void jCombojugadores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombojugadores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombojugadores1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     // Cargar jugadores en jCombojugadores
    cargarJugadores(jCombojugadores, jugadoresDisponibles);
    
    // Cargar jugadores en jCombojugadores1
    cargarJugadores(jCombojugadores1, jugadoresDisponibles);
    
    // Agregar ActionListener a jCombojugadores para manejar la selección de jugadores
    jCombojugadores.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Obtener el jugador seleccionado en jCombojugadores
            String jugadorSeleccionado = (String) jCombojugadores.getSelectedItem();
            
            // Eliminar el jugador seleccionado de jCombojugadores1
            eliminarJugadorDeComboBox(jugadorSeleccionado, jCombojugadores1);
        }
    });
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBackToinicio1;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jButton_iniciar;
    private javax.swing.JComboBox<String> jCombojugadores;
    private javax.swing.JComboBox<String> jCombojugadores1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPHome2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlBackground;
    // End of variables declaration//GEN-END:variables
}
